version: '3.2'

services:

  redmine:
    build:
      context: ./_docker/bin
    restart: always
    ports:
      - ${REDMINE_PORT}:3000
    volumes:
      - public_html:/usr/src/redmine
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: ${REDMINE_DB_PASSWORD}
      REDMINE_SECRET_KEY_BASE: supersecretkey
    
  db:
    image: mysql:5.7
    restart: always
    ports:
     - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
     - db_data:/var/lib/mysql
    command:
     - --character-set-server=utf8mb4
     - --collation-server=utf8mb4_unicode_ci

volumes:
  db_data: